Ab#4765
champtc/opencti pull request #175
Opened 2022-03-04 12:13 UTC by sachin755

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-03-04 13:34 UTC, CyberDaedalus00 commented on opencti-platform/opencti-front/src/private/components/riskAssessment/risks/remediations/RequiredResourcePopover.js
> +    const types = ["Party", "Component", "User", "Location", "Inventory-Item", "Party"];
The values for the "Type" box in the UI should be populated by performing an GraphQL introspection query on the SubjectType.  The query is shown below.  As was the case with Assets, the description field contains what should be shown to the user, where the name contains the value that is to be used in other GraphQL calls.

query SubjectTypeIntrospection {
  __type(name: "SubjectType") {
    name
    enumValues {
      name
      description
    }
  }
}

2022-03-04 13:43 UTC, CyberDaedalus00 reviewed
1. The title on the modal dialog that comes up when you press the '+' next to label "Required Resources" should be "Required Resource".  Its currently "Require Resource".

2. The breadcrumb should display the name of the risk, not the id of the risk
3. The breadcrumb is missing from Remediation details page

2022-03-07 22:45 UTC, CyberDaedalus00 requested changes
While the updates to the 'Required Resource' modal dialog box looks correct, it appears from the fact that no GraphQL requests are being made, that the modal is a static implementation.

The contents of the 'Type' box should contain the value of the 'description' field  from performing a GraphQL introspection query against the SubjectType enumeration.  The select item's 'name' value is used to determine which type of query to make in order to populate the 'Resource' box.

For example, if the user select "Interview Party" in the 'Type' box, the 'Resource' box is populated with a list of all the Party objects defined in the system from the GraphQL query 'parties'.  If the user selects "Location" in the 'Type' box, the 'Resource' box is populated with a list of all the OscalLocation objects return from a GraphQL query to the 'oscalLocations'

2022-03-09 23:28 UTC, r-joyce approved these changes

2022-03-09 23:28 UTC, merged