AB#5047
champtc/opencti pull request #267
Opened 2022-04-18 12:13 UTC by sachin755

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-04-20 15:21 UTC, johnjdl commented
Code changes tested locally, @DallasP9124 @r-joyce please review and merge.

2022-04-20 16:01 UTC, DallasP9124 requested changes

2022-04-20 16:01 UTC, BigBallard commented on opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreation.js
> +      onError: (err => (console.error('DeviceCreationError', err))),
@sachin755 errors need to be displayed to the user for now on. If you console an error, a toast needs to also be used to let the user know. Refer to `utils/bakedToast.js` for the simple API to do so. Short messages (3-5 words max).

2022-04-21 17:30 UTC, DallasP9124 approved these changes
@r-joyce good

2022-04-21 18:07 UTC, r-joyce approved these changes

2022-04-21 18:07 UTC, merged