AB#5002
champtc/opencti pull request #275
Opened 2022-04-19 11:55 UTC by sachin755

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-04-19 15:10 UTC, johnjdl commented
Looks good on the local build, @DallasP9124 and/or @r-joyce please review and merge.

2022-04-19 15:53 UTC, BigBallard commented
@johnjdl waiting to hear back from Beth, this is not really a bug. Based on the card, these values are expected and are correct even though they both have the vulnerability ID. If I do not get to this by EOD then please ping me to update.

2022-04-19 18:38 UTC, DallasP9124 commented
@johnjdl I am actually confused by the code changes, wasnt he supposed to remove the description and not the name in the RiskObservationLine ?

2022-04-19 18:42 UTC, johnjdl commented
@DallasP9124 You are right. That is what the ticket instructed them to do. I'm noticing in the RiskObesrationLine that name was removed and not the description. I will screenshot the code change and send it back.

2022-04-20 13:52 UTC, johnjdl commented
@DallasP9124 @r-joyce this has been corrected, please review and merge.

2022-04-20 15:44 UTC, BigBallard commented on opencti-platform/opencti-front/src/private/components/riskAssessment/risks/RiskObservationLine.js
> -                    {observation.node.name && t(observation.node.name)}
@AMAN-SHARMA-82591 this needs to be corrected. The name should be rendering, not the description.

2022-04-20 15:45 UTC, BigBallard requested changes
@AMAN-SHARMA-82591 I made a note of what needs to be fixed. You removed the name and added the description where the name should have stayed.

2022-04-20 17:03 UTC, sachin755 commented on opencti-platform/opencti-front/src/private/components/riskAssessment/risks/RiskObservationLine.js
> -                    {observation.node.name && t(observation.node.name)}
@DallasP9124  The page you've address is RiskObservationLine which as we've talked in today's meeting will only have name and created-date populated which we have added. If I add another name in that component there will be two fields with same value in it. Is that what you want?

2022-04-20 18:02 UTC, r-joyce approved these changes

2022-04-21 13:33 UTC, johnjdl commented
@DallasP9124 @r-joyce please hold off on merging this one.

2022-04-21 14:12 UTC, merged