AB#5003
champtc/opencti pull request #292
Opened 2022-04-22 12:12 UTC by sachin755

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-04-22 15:41 UTC, johnjdl commented
Working correctly in local build, @DallasP9124 @r-joyce please review and merge.

2022-04-22 16:33 UTC, BigBallard requested changes

2022-04-22 16:33 UTC, BigBallard commented on opencti-platform/opencti-front/src/private/components/riskAssessment/risks/RiskObservation.js
> +                return toastGenericError('Request Failed');
@sachin755 please continue to log errors in `console.error`. Refer to my comment in #287 please.

2022-04-22 16:33 UTC, BigBallard commented on opencti-platform/opencti-front/src/private/components/riskAssessment/risks/RiskObservationPopover.js
> +    console.log('RiskObservationPopover', data);
Please do not include `console.log` statements in your PR's.

2022-04-25 13:38 UTC, merged

2022-04-25 16:08 UTC, BigBallard commented
@johnjdl don't forget to delete branches after merge 😉