AB#5015
champtc/opencti pull request #317
Opened 2022-05-02 11:59 UTC by sachin755

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-05-05 19:13 UTC, johnjdl commented
@r-joyce please review and merge once the other priority PRs are done.

2022-05-05 21:29 UTC, r-joyce requested changes
Everything looks good to me besides the occasional Lorem Ipsum or hard-coded value.

@johnjdl @kevinh4 Can we get these fixed before merging?

2022-05-05 21:29 UTC, r-joyce commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/responsibleParties/DataSourceResponsiblePartiesDeletion.js
> +                {t('Are you sure you’d like to delete this Risk?')}
Guessing this should say "Responsible Parties" and not "Risk"?

2022-05-05 21:29 UTC, r-joyce commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/responsibleParties/EntityResponsiblePartyCard.js
> +                  {t('Lorem Ipsum')}
Lorem Ipsum

2022-05-05 21:29 UTC, r-joyce commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/responsibleParties/EntityResponsiblePartyDetails.js
> +                {t('Lorem Ipsum')}
Lorem Ipsum

2022-05-05 21:29 UTC, r-joyce commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/responsibleParties/EntityResponsiblePartyDetails.js
> +                {t('Jun 3, 2022')}
Hard-coded date

2022-05-05 21:29 UTC, r-joyce commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/responsibleParties/EntityResponsiblePartyDetails.js
> +                {t('Lorem Ipsum')}
Lorem Ipsum

2022-05-05 21:29 UTC, r-joyce commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/responsibleParties/EntityResponsiblePartyDetails.js
> +                {t('Lorem Ipsum')}
Lorem Ipsum

2022-05-05 21:29 UTC, r-joyce commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/responsibleParties/EntityResponsiblePartyDetails.js
> +                    {t('Lorem Ipsum')}
Lorem Ipsum

2022-05-05 21:29 UTC, r-joyce commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/responsibleParties/EntityResponsiblePartyDetails.js
> +                {t('IEP: WHITE')}
Hard-coded TLP value

2022-05-06 18:15 UTC, johnjdl commented
@r-joyce looks like Secutree made the fixes you requested. Go ahead and review again and merge when you have a moment.

2022-05-06 19:29 UTC, johnjdl commented
@r-joyce Let's hold off on this 5017 and 5019 since it looks like there are some queries provided by Paul that Secutree will need to include.

2022-05-09 16:51 UTC, r-joyce approved these changes
Looks good to me 👍

2022-05-11 21:58 UTC, johnjdl commented
@r-joyce Let's hold off on this one.

2022-05-16 19:04 UTC, r-joyce approved these changes
Looks good to me 👍

2022-05-17 19:05 UTC, merged