AB#5017
champtc/opencti pull request #319
Opened 2022-05-02 12:01 UTC by sachin755

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-05-05 19:24 UTC, johnjdl commented
@r-joyce please review and merge once the other priority PRs are done and development is bumped. These (5015 and 5017) are lower priorities.

2022-05-05 22:29 UTC, r-joyce requested changes
@johnjdl @kevinh4 Need some minor changes for hard-coded values

2022-05-05 22:29 UTC, r-joyce commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/assessment_platform/EntitiesAssessmentPlatformsDeletion.js
> +                {t('Are you sure you’d like to delete this Role?')}
Should it be "Role" here?

2022-05-05 22:29 UTC, r-joyce commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/assessment_platform/EntityAssessmentPlatformDetails.js
> +                {t('IEP: WHITE')}
Hard-coded TLP value

2022-05-06 18:15 UTC, johnjdl commented
@r-joyce looks like Secutree made the fixes you requested. Go ahead and review again and merge when you have a moment.

2022-05-06 19:30 UTC, johnjdl commented
@r-joyce Let's hold off on this 5015 and 5019 since it looks like there are some queries provided by Paul that Secutree will need to include.

2022-05-11 19:27 UTC, r-joyce approved these changes
Looks good to me 👍

2022-05-11 20:46 UTC, johnjdl commented
@r-joyce go ahead and merge along with 5014. Please DO NOT merge 5019, it needs work still and has been sent back to active.

2022-05-12 15:17 UTC, johnjdl commented
@r-joyce please merge this along with 5014 and 5019.

2022-05-12 15:21 UTC, johnjdl commented
Nevermind @r-joyce please hold on merging 5014, 5017, and 5019 for now.

2022-05-16 14:27 UTC, johnjdl commented
@r-joyce please review and merge these first today.

5014 - Data Entity: Parties
5019 - Data Entity: Locations
*5017 - Data Entity: Assessment Platform
5195 - Disable merge button

2022-05-18 15:09 UTC, merged