AB#5019
champtc/opencti pull request #343
Opened 2022-05-06 12:01 UTC by sachin755

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-05-06 18:16 UTC, johnjdl commented
@r-joyce review and merge when you have a moment.

2022-05-06 19:22 UTC, johnjdl commented
@r-joyce hold off on this one, still some queries needed to implement into this one.

2022-05-11 00:06 UTC, r-joyce requested changes

2022-05-11 00:06 UTC, r-joyce commented on opencti-platform/opencti-front/src/relay/environmentDarkLight.js
> +    headers['X-Cyio-Client'] = '30f033d4-e90d-44f9-8ce0-36597ff08c93';
I'm guessing this was a mistake

2022-05-12 15:17 UTC, johnjdl commented
@r-joyce go ahead and merge this along with 5014 and 5017.

2022-05-12 15:20 UTC, johnjdl commented
@r-joyce nevermind, hold on merging 5014, 5017, and 5019 for now.

2022-05-16 14:26 UTC, johnjdl commented
@r-joyce please review and merge these first today.

5014 - Data Entity: Parties
*5019 - Data Entity: Locations
5017 - Data Entity: Assessment Platform
5195 - Disable merge button

2022-05-17 22:19 UTC, r-joyce approved these changes
Looks good 👍

2022-05-17 22:19 UTC, r-joyce commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/locations/EntityLocationCard.js
> +                  {t('Lorem Ipsum')}
Lorem Ipsum

2022-05-17 22:19 UTC, merged