AB#5014
champtc/opencti pull request #355
Opened 2022-05-09 11:52 UTC by sachin755

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-05-11 20:46 UTC, johnjdl commented
@r-joyce go ahead and merge along with 5017. Please DO NOT merge 5019, it needs work still and has been sent back to active.

2022-05-12 15:16 UTC, johnjdl commented
@r-joyce please merge this along with 5017 and 5019.

2022-05-12 15:20 UTC, johnjdl commented
Nevermind @r-joyce please hold on merging 5014, 5017, and 5019 for now.

2022-05-16 14:26 UTC, johnjdl commented
@r-joyce please review and merge these first today.

*5014 - Data Entity: Parties
5019 - Data Entity: Locations
5017 - Data Entity: Assessment Platform
5195 - Disable merge button

2022-05-16 18:35 UTC, r-joyce requested changes
Other than the one Lorem Ipsum, looks good

2022-05-16 18:35 UTC, r-joyce commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/parties/EntityPartyCard.js
> +                  {t('Lorem Ipsum')}
Lorem Ipsum

2022-05-16 18:53 UTC, johnjdl commented on opencti-platform/opencti-front/src/private/components/dataEntities/data/parties/EntityPartyCard.js
> +                  {t('Lorem Ipsum')}
@r-joyce I removed the Lorem Ipsum here.

2022-05-16 19:04 UTC, merged